version: '3'

services:
  webgoat:
    build:
      dockerfile: docker/Dockerfile
      context: webgoat-container
    environment:
      - WEBWOLF_HOST=webwolf
      - WEBWOLF_PORT=9090
      - TZ=Europe/Amsterdam
    ports:
      - "8080:8080"
      - "9001:9001"
    volumes:
      - .:/home/webgoat/.webgoat
    working_dir: /home/webgoat
  webwolf:
    build:
      dockerfile: webwolf/Dockerfile
      context: webwolf
    ports:
      - "9090:9090"
    command: --spring.datasource.url=jdbc:hsqldb:hsql://webgoat:9001/webgoat --server.address=0.0.0.0
    depends_on:
            - webgoat
